/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_layouts`; params?: Router.UnknownInputParams; } | { pathname: `/attendance-history`; params?: Router.UnknownInputParams; } | { pathname: `/attendance-verification`; params?: Router.UnknownInputParams; } | { pathname: `/demo-instructions`; params?: Router.UnknownInputParams; } | { pathname: `/leave-requests`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register_hr` | `/register_hr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/hr/company-location`; params?: Router.UnknownInputParams; } | { pathname: `/hr`; params?: Router.UnknownInputParams; } | { pathname: `/hr/leave-requests`; params?: Router.UnknownInputParams; } | { pathname: `/hr/register_worker`; params?: Router.UnknownInputParams; } | { pathname: `/hr/reports`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_layouts`; params?: Router.UnknownOutputParams; } | { pathname: `/attendance-history`; params?: Router.UnknownOutputParams; } | { pathname: `/attendance-verification`; params?: Router.UnknownOutputParams; } | { pathname: `/demo-instructions`; params?: Router.UnknownOutputParams; } | { pathname: `/leave-requests`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register_hr` | `/register_hr`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/hr/company-location`; params?: Router.UnknownOutputParams; } | { pathname: `/hr`; params?: Router.UnknownOutputParams; } | { pathname: `/hr/leave-requests`; params?: Router.UnknownOutputParams; } | { pathname: `/hr/register_worker`; params?: Router.UnknownOutputParams; } | { pathname: `/hr/reports`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_layouts${`?${string}` | `#${string}` | ''}` | `/attendance-history${`?${string}` | `#${string}` | ''}` | `/attendance-verification${`?${string}` | `#${string}` | ''}` | `/demo-instructions${`?${string}` | `#${string}` | ''}` | `/leave-requests${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register_hr${`?${string}` | `#${string}` | ''}` | `/register_hr${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/schedule${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `/hr/company-location${`?${string}` | `#${string}` | ''}` | `/hr${`?${string}` | `#${string}` | ''}` | `/hr/leave-requests${`?${string}` | `#${string}` | ''}` | `/hr/register_worker${`?${string}` | `#${string}` | ''}` | `/hr/reports${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_layouts`; params?: Router.UnknownInputParams; } | { pathname: `/attendance-history`; params?: Router.UnknownInputParams; } | { pathname: `/attendance-verification`; params?: Router.UnknownInputParams; } | { pathname: `/demo-instructions`; params?: Router.UnknownInputParams; } | { pathname: `/leave-requests`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register_hr` | `/register_hr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/hr/company-location`; params?: Router.UnknownInputParams; } | { pathname: `/hr`; params?: Router.UnknownInputParams; } | { pathname: `/hr/leave-requests`; params?: Router.UnknownInputParams; } | { pathname: `/hr/register_worker`; params?: Router.UnknownInputParams; } | { pathname: `/hr/reports`; params?: Router.UnknownInputParams; };
    }
  }
}
